name: Auto Backup to Other GitHub Repo

on:
  push:
    branches:
      - '**'  # Match pushes on all branches

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to Backup Repo
        run: |
          git config --global user.name "AutoBackupBot"
          git config --global user.email "backup@github.com"
          git remote add mirror https://x-access-token:${{ secrets.TARGET_PAT }}@github.com/SoumyadeepEasydo/easyodowebapp.git
          git push --mirror mirror
